In [381]:
import numpy as np

class Bandit():
    
    def __init__(self, N, est=None, counts=None):
        self.Nmachines=N
        self.arm_values=np.random.rand(N)
        
        if est is None:
            self.est_values = np.zeros(N)
        else:
            self.est_values = est
        
        if counts is None:
            self.useage_values = np.zeros(N)
        else:
            self.useage_values = counts
    
    def get_reward(self,action):
        rand_num=np.random.random()
        if rand_num < self.arm_values[action]:
            return 1
        else:
            return 0
    
    def greedy_hour_select(self, epsilon):
        rand_num=np.random.random()
        if rand_num>epsilon:
            return np.argmax(self.est_values, axis=0)
        else:
            a=np.random.randint(self.Nmachines)
            return (a)
          
    def UCP_hour_select(self):
        totalN = self.useage_values.sum(axis=1).reshape(-1, 1)
        uncertanty = np.sqrt(2*np.log(totalN+1)/self.useage_values)
        return np.argmax(self.est_values + uncertanty, axis=1)

    def update_est(self, action, reward):
        for row, index in enumerate(action):
            self.useage_values[row, index]+=1
            self.est_values[row,index] = (self.est_values[row, index]*(self.useage_values[row, index]-1)+reward[row])/np.float(self.useage_values[row, index])

    def bandit_test(self, NPull, epsilon=0.02):
        reward_history=[]
        for i in range(NPull):
            # machine=bandit.greedy_machine_select(epsilon)
            machine = bandit.UCP_hour_select()
            reward=bandit.get_reward(machine)
            bandit.update_est(machine,reward)
            reward_history.append(reward)
        print(self.est_values)
        print(self.useage_values)

In [382]:
bandit = Bandit(12)

In [383]:
bandit.arm_values = 0.1*np.ones(12)
bandit.arm_values[3] = 0.5
bandit.arm_values

array([0.1, 0.1, 0.1, 0.5, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1])

In [384]:
bandit.bandit_test(10)


AxisError: axis 1 is out of bounds for array of dimension 1

In [385]:
import pandas as pd

In [386]:
df = pd.read_csv('Heart.csv')

In [387]:
hour_counts_cols = ['Age', 'RestBP', 'Chol']
est_values_cols = ['Oldpeak', 'Ca', 'RestECG']
hour_counts = df[hour_counts_cols].values
est_values = df[est_values_cols].values

In [388]:
bandit = Bandit(3, est_values, hour_counts)

In [389]:
index = bandit.UCP_hour_select()
df['next_index'] = index
df['next_attempt'] = np.array(hour_counts_cols)[index]
df
# df.to_csv('my_filename.csv')

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
5             6   56    1    nontypical     120   236    0        0    178   
6             7   62    0  asymptomatic     140   268    0        2    160   
7             8   57    0  asymptomatic     120   354    0        0    163   
8             9   63    1  asymptomatic     130   254    0        2    147   
9            10   53    1  asymptomatic     140   203    1        2    155   
10           11   57    1  asymptomatic     140   192    0        0    148   
11           12   56    0    nontypical     140   294    0        2    153   
12           13   56    1    nonanginal     130   256    1        2    142   
13           14   44    1    nontypical     120   263    0        0    173   
14           15   52    1    nonanginal     172   199    1        0    162   
15           16   57    1    nonanginal     150   168    0        0    174   
16           17   48    1    nontypical     110   229    0        0    168   
17           18   54    1  asymptomatic     140   239    0        0    160   
18           19   48    0    nonanginal     130   275    0        0    139   
19           20   49    1    nontypical     130   266    0        0    171   
20           21   64    1       typical     110   211    0        2    144   
21           22   58    0       typical     150   283    1        2    162   
22           23   58    1    nontypical     120   284    0        2    160   
23           24   58    1    nonanginal     132   224    0        2    173   
24           25   60    1  asymptomatic     130   206    0        2    132   
25           26   50    0    nonanginal     120   219    0        0    158   
26           27   58    0    nonanginal     120   340    0        0    172   
27           28   66    0       typical     150   226    0        0    114   
28           29   43    1  asymptomatic     150   247    0        0    171   
29           30   40    1  asymptomatic     110   167    0        2    114   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
273         274   71    0  asymptomatic     112   149    0        0    125   
274         275   59    1       typical     134   204    0        0    162   
275         276   64    1       typical     170   227    0        2    155   
276         277   66    0    nonanginal     146   278    0        2    152   
277         278   39    0    nonanginal     138   220    0        0    152   
278         279   57    1    nontypical     154   232    0        2    164   
279         280   58    0  asymptomatic     130   197    0        0    131   
280         281   57    1  asymptomatic     110   335    0        0    143   
281         282   47    1    nonanginal     130   253    0        0    179   
282         283   55    0  asymptomatic     128   205    0        1    130   
283         284   35    1    nontypical     122   192    0        0    174   
284         285   61    1  asymptomatic     148   203    0        0    161   
285         286   58    1  asymptomatic     114   318    0        1    140   
286         287   58    0  asymptomatic     170   225    1        2    146   
287         288   58    1    nontypical     125   220    0        0    144   
288         289   56    1    nontypical     130   221    0        2    163   
289         290   56    1    nontypical     120   240    0        0    169   
290         291   67    1    nonanginal     152   212    0        2    150   
291         292   55    0    nontypical     132   342    0        0    166   
292         293   44    1  

In [394]:
# result = df['result'] 
# index = df ['next_index']
reward = np.where(np.random.rand(len(df)) < 0.1, 1, 0)
index = df['next_index']

reward = reward.reshape(-1, 1)
bandit.update_est(index, reward)

In [395]:
print(bandit.est_values)
print(bandit.useage_values)

[[2.19545455 0.         2.        ]
 [1.5        2.95705521 2.        ]
 [2.48857143 2.         2.        ]
 [3.2375     0.         0.        ]
 [1.4        0.         1.97101449]
 [0.75932203 0.         0.        ]
 [3.44923077 2.         2.        ]
 [0.58666667 0.         0.        ]
 [1.4        1.         1.98054475]
 [2.93392857 0.         2.        ]
 [0.38       0.         0.        ]
 [1.3        0.         1.98316498]
 [0.6        1.         1.98069498]
 [0.         0.         0.        ]
 [0.49090909 0.         0.        ]
 [1.55333333 0.         0.        ]
 [0.94117647 0.         0.        ]
 [1.13684211 0.         0.        ]
 [0.18823529 0.         0.        ]
 [0.58461538 0.         0.        ]
 [1.8        0.         1.97663551]
 [1.         0.         1.97902098]
 [1.71147541 0.         2.        ]
 [3.05901639 2.         2.        ]
 [2.28571429 2.         2.        ]
 [1.50943396 0.         0.        ]
 [0.         0.         0.        ]
 [2.50144928 0.         0.  